export const DISTRITOS_LIMA = [
  'Ancón',
  'Ate',
  'Barranco',
  'Breña',
  'Carabayllo',
  'Chaclacayo',
  'Chorrillos',
  'Cieneguilla',
  'Comas',
  'El Agustino',
  'Independencia',
  'Jesús María',
  'La Molina',
  'La Victoria',
  'Lima',
  'Lince',
  'Los Olivos',
  'Lurigancho',
  'Lurín',
  'Magdalena del Mar',
  'Miraflores',
  'Pachacámac',
  'Pucusana',
  'Pueblo Libre',
  'Puente Piedra',
  'Punta Hermosa',
  'Punta Negra',
  'Rímac',
  'San Bartolo',
  'San Borja',
  'San Isidro',
  'San Juan de Lurigancho',
  'San Juan de Miraflores',
  'San Luis',
  'San Martín de Porres',
  'San Miguel',
  'Santa Anita',
  'Santa María del Mar',
  'Santa Rosa',
  'Santiago de Surco',
  'Surquillo',
  'Villa El Salvador',
  'Villa María del Triunfo',
  'Villa Rica',
];

export const UNIVERSIDADES_LIMA = [
  'PUCP - Pontificia Universidad Católica del Perú',
  'UNMSM - Universidad Nacional Mayor de San Marcos',
  'UP - Universidad del Pacífico',
  'ULIMA - Universidad de Lima',
  'USIL - Universidad San Ignacio de Loyola',
  'USMP - Universidad San Martín de Porres',
  'UPC - Universidad Peruana de Ciencias Aplicadas',
  'UTP - Universidad Tecnológica del Perú',
  'UNI - Universidad Nacional de Ingeniería',
  'UNFV - Universidad Nacional Federico Villarreal',
  'UCH - Universidad de Ciencias y Humanidades',
  'UPCH - Universidad Peruana Cayetano Heredia',
  'UAP - Universidad Alas Peruanas',
  'UNIFÉ - Universidad Femenina del Sagrado Corazón',
  'UIGV - Universidad Inca Garcilaso de la Vega',
  'UPN - Universidad Privada del Norte',
  'UPAO - Universidad Privada Antenor Orrego',
  'UPSJB - Universidad Privada San Juan Bautista',
  'UCSUR - Universidad Científica del Sur',
  'UPCV - Universidad Peruana de Ciencias e Informática',
];

